#ifndef PARKING_CLOUD_CONFIG_H
#define PARKING_CLOUD_CONFIG_H

#define WIFI_SSID "your-wifi-ssid"
#define WIFI_PASSWORD "your-wifi-password"

#define CLOUD_UPLOAD_URL "CLOUD_UPLOAD_URL"
#define CLOUD_RESERVATION_SYNC_URL "CLOUD_RESERVATION_SYNC_URL"
#define CLOUD_DEVICE_ID "CLOUD_DEVICE_ID"
#define CLOUD_DEVICE_KEY "CLOUD_DEVICE_KEY"

#define WIFI_RECONNECT_INTERVAL_MS 10000UL
#define UPLOAD_RETRY_INTERVAL_MS 5000UL
#define RESERVATION_SYNC_INTERVAL_MS 5000UL

#endif
